#!/usr/bin/env python3
"""Extract an ARM9 function from the Sonic Rush NDS ROM and build an ARMIPS
reassembly harness for patching.

Usage:
    extract.py <ram_addr> [size]
    extract.py <ram_addr>           # size auto-detected via r2 (afi)

Outputs (in OUT_DIR, default ./disassembly):
    <addr>.bin    raw ARM9 bytes
    <addr>.asm    ARMIPS source that re-assembles the function at its RAM addr

mem->file mapping: file = 0x4000 + (ram - 0x02000000)
ARM9 load addr = 0x02000800
"""

import os
import re
import struct
import subprocess
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROM = os.environ.get("SONIC_RUSH_ROM", os.path.join(PROJECT_ROOT, "games", "sonic-rush.nds"))
ARMIPS = os.environ.get("ARMIPS", os.path.join(PROJECT_ROOT, "tools", "armips"))
OUT_DIR = os.environ.get("DISASSEMBLY_DIR", os.path.join(PROJECT_ROOT, "disassembly"))
MEM_BASE = 0x02000000
FILE_BASE = 0x4000

TARGETS = {
    0x02000b24: "main per-frame loop",
    0x0200d998: "task/screen controller IRQ6 input transition handler",
    0x02035134: "input debounce/edge read",
    0x02036a0c: "object-list per-frame walker",
    0x02036bfc: "object-list insert",
    0x02036aec: "object-list camera-space lookup",
    0x0203363c: "hitbox-frame setup from action data",
    0x0206c3d0: "player per-frame update cb",
    0x0206919c: "velocity injection into raw input (bindings)",
    0x020694b0: "movement/accel handler",
    0x020657dc: "movement+collision resolution",
    0x020648c4: "ground collision + slope snap",
    0x0204da44: "player spawn",
    0x02067ddc: "scripted attract/demo sequence controller",
    0x02068094: "scripted attract/demo sequence spawner",
}


def mem_to_file(ram):
    return FILE_BASE + (ram - MEM_BASE)


def find_size_r2(ram):
    """Use r2 afi to get function size in bytes."""
    cmd = ["r2", "-q", "-c", f"aaa; s {ram:#x}; afi", "-2", ROM]
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=120).stdout
    except FileNotFoundError:
        return None
    m = re.search(r"size:\s+(\d+)", out)
    return int(m.group(1)) if m else None


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1
    ram = int(sys.argv[1], 0)
    size = int(sys.argv[2], 0) if len(sys.argv) > 2 else None
    if size is None:
        size = find_size_r2(ram)
        if size is None:
            print(f"could not auto-detect size for {ram:#x}; pass size explicitly")
            return 1

    data = open(ROM, "rb").read()
    off = mem_to_file(ram)
    if off < 0 or off + size > len(data):
        print(f"out of range: ram={ram:#x} off={off:#x} size={size:#x}")
        return 1
    blob = data[off:off + size]

    os.makedirs(OUT_DIR, exist_ok=True)
    base = os.path.join(OUT_DIR, f"{ram:#010x}")
    with open(base + ".bin", "wb") as f:
        f.write(blob)

    with open(base + ".asm", "w") as f:
        f.write("// Auto-generated by extract.py\n")
        f.write(f"// Function: {TARGETS.get(ram, 'unknown')}\n")
        f.write(f"// Range: {ram:#x}..{ram + size:#x} ({size:#x} bytes)\n\n")
        f.write(".nds\n.arm\n")
        # Use relative paths for portability
        rel_bin = os.path.relpath(base + ".bin", OUT_DIR)
        out_name = os.path.join(OUT_DIR, f"{ram:#010x}.patched.nds")
        rel_out = os.path.relpath(out_name, OUT_DIR)
        f.write(f'.create "{rel_out}", {MEM_BASE:#x}\n')
        f.write(f".org {ram:#x}\n")
        f.write(f'.incbin "{rel_bin}"\n')
        f.write(".close\n")

    # verify reassembly is byte-exact against the ROM
    ok = False
    if os.system(f'cd "{OUT_DIR}" && "{ARMIPS}" "{ram:#010x}.asm" >/dev/null 2>&1') == 0:
        rom = open(ROM, "rb").read()
        patched = os.path.join(OUT_DIR, f"{ram:#010x}.patched.nds")
        out = open(patched, "rb").read()
        ro = mem_to_file(ram)
        oo = ram - MEM_BASE
        ok = rom[ro:ro + size] == out[oo:oo + size]
        os.unlink(patched)

    print(f"wrote {base}.bin ({size} bytes) + {base}.asm; reassembly {'MATCHES' if ok else 'MISMATCH'} ROM")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
