#!/usr/bin/env python3
"""Extract overlays from Sonic Rush NDS ROM.

The NDS ROM contains overlay tables that describe where each overlay's
code and data are stored. This tool parses those tables and extracts
the overlays to separate files.

Usage:
    extract-overlays.py [rom_path] [output_dir]

Output:
    <output_dir>/ov0.bin    - Overlay 0 (gameplay)
    <output_dir>/ov1.bin    - Overlay 1 (title/menu)
    <output_dir>/ov0.map    - Overlay 0 memory map
    <output_dir>/ov1.map    - Overlay 1 memory map
    <output_dir>/overlays.json - Overlay metadata
"""

import json
import os
import struct
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROM = os.environ.get("SONIC_RUSH_ROM", os.path.join(PROJECT_ROOT, "games", "sonic-rush.nds"))
OUT_DIR = os.environ.get("OVERLAY_DIR", os.path.join(PROJECT_ROOT, "overlays"))

# NDS header offsets
NDS_HEADER_SIZE = 0x200
ARM9_OFFSET_ADDR = 0x20
ARM9_SIZE_ADDR = 0x2C
ARM7_OFFSET_ADDR = 0x30
ARM7_SIZE_ADDR = 0x3C
OVERLAY_TABLE_OFFSET_ADDR = 0x50
OVERLAY_TABLE_SIZE_ADDR = 0x54

# Overlay table entry format (32 bytes each)
# struct OverlayEntry {
#     u32 ram_addr;      // +0x00: RAM address
#     u32 ram_size;      // +0x04: RAM size
#     u32 bss_size;      // +0x08: BSS size
#     u32 init_start;    // +0x0C: Init function start
#     u32 init_end;      // +0x10: Init function end
#     u32 file_id;       // +0x14: File ID in ROM
#     u32 rom_offset;    // +0x18: ROM offset of overlay data
#     u32 rom_size;      // +0x1C: ROM size of overlay data
# }
OVERLAY_ENTRY_SIZE = 32

# Known overlay ranges (from runtime analysis)
OVERLAY_RANGES = {
    0: {"name": "gameplay", "ram_start": 0x02320000, "ram_end": 0x02350000},
    1: {"name": "title", "ram_start": 0x022c5c80, "ram_end": 0x0231f01f},
}

def parse_header(data):
    """Parse NDS ROM header."""
    header = {}
    header["arm9_offset"] = struct.unpack_from("<I", data, ARM9_OFFSET_ADDR)[0]
    header["arm9_size"] = struct.unpack_from("<I", data, ARM9_SIZE_ADDR)[0]
    header["arm7_offset"] = struct.unpack_from("<I", data, ARM7_OFFSET_ADDR)[0]
    header["arm7_size"] = struct.unpack_from("<I", data, ARM7_SIZE_ADDR)[0]
    header["overlay_table_offset"] = struct.unpack_from("<I", data, OVERLAY_TABLE_OFFSET_ADDR)[0]
    header["overlay_table_size"] = struct.unpack_from("<I", data, OVERLAY_TABLE_SIZE_ADDR)[0]
    return header

def parse_overlay_table(data, offset, size):
    """Parse overlay table from ROM data."""
    overlays = []
    num_entries = size // OVERLAY_ENTRY_SIZE
    
    for i in range(num_entries):
        entry_offset = offset + (i * OVERLAY_ENTRY_SIZE)
        if entry_offset + OVERLAY_ENTRY_SIZE > len(data):
            break
            
        entry = {}
        entry["id"] = i
        entry["ram_addr"] = struct.unpack_from("<I", data, entry_offset)[0]
        entry["ram_size"] = struct.unpack_from("<I", data, entry_offset + 4)[0]
        entry["bss_size"] = struct.unpack_from("<I", data, entry_offset + 8)[0]
        entry["init_start"] = struct.unpack_from("<I", data, entry_offset + 12)[0]
        entry["init_end"] = struct.unpack_from("<I", data, entry_offset + 16)[0]
        entry["file_id"] = struct.unpack_from("<I", data, entry_offset + 20)[0]
        entry["rom_offset"] = struct.unpack_from("<I", data, entry_offset + 24)[0]
        entry["rom_size"] = struct.unpack_from("<I", data, entry_offset + 28)[0]
        
        # Only include overlays with valid data
        if entry["rom_size"] > 0 or entry["ram_size"] > 0:
            overlays.append(entry)
    
    return overlays

def extract_overlay(data, overlay, output_dir):
    """Extract a single overlay to file."""
    overlay_id = overlay["id"]
    rom_offset = overlay["rom_offset"]
    rom_size = overlay["rom_size"]
    ram_addr = overlay["ram_addr"]
    ram_size = overlay["ram_size"]
    bss_size = overlay["bss_size"]
    
    # Create output filename
    name = OVERLAY_RANGES.get(overlay_id, {}).get("name", f"ov{overlay_id}")
    bin_path = os.path.join(output_dir, f"{name}.bin")
    map_path = os.path.join(output_dir, f"{name}.map")
    
    # Extract binary data
    if rom_size > 0 and rom_offset + rom_size <= len(data):
        bin_data = data[rom_offset:rom_offset + rom_size]
        with open(bin_path, "wb") as f:
            f.write(bin_data)
        print(f"  {name}.bin: {rom_size} bytes from ROM offset {rom_offset:#x}")
    else:
        print(f"  WARNING: {name} has no ROM data (offset={rom_offset:#x}, size={rom_size:#x})")
    
    # Create memory map
    with open(map_path, "w") as f:
        f.write(f"# Overlay {overlay_id} ({name}) Memory Map\n")
        f.write(f"# Generated by extract-overlays.py\n\n")
        f.write(f"RAM Address: {ram_addr:#010x}\n")
        f.write(f"RAM Size:    {ram_size:#x} ({ram_size} bytes)\n")
        f.write(f"BSS Size:    {bss_size:#x} ({bss_size} bytes)\n")
        f.write(f"ROM Offset:  {rom_offset:#010x}\n")
        f.write(f"ROM Size:    {rom_size:#x} ({rom_size} bytes)\n")
        if overlay["init_start"] and overlay["init_end"]:
            f.write(f"Init Start:  {overlay['init_start']:#010x}\n")
            f.write(f"Init End:    {overlay['init_end']:#010x}\n")
        f.write(f"\n# Memory Layout\n")
        f.write(f"{ram_addr:#010x} - {ram_addr + ram_size:#010x}  .text/.data (from ROM)\n")
        f.write(f"{ram_addr + ram_size:#010x} - {ram_addr + ram_size + bss_size:#010x}  .bss (zeroed at load)\n")
    
    return bin_path

def main():
    if len(sys.argv) > 1:
        rom_path = sys.argv[1]
    else:
        rom_path = ROM
    
    if len(sys.argv) > 2:
        output_dir = sys.argv[2]
    else:
        output_dir = OUT_DIR
    
    if not os.path.exists(rom_path):
        print(f"ERROR: ROM not found at {rom_path}")
        print("Set SONIC_RUSH_ROM env var or pass path as argument")
        return 1
    
    print(f"ROM: {rom_path}")
    print(f"Output: {output_dir}")
    
    # Read ROM
    with open(rom_path, "rb") as f:
        data = f.read()
    
    # Parse header
    header = parse_header(data)
    print(f"\nNDS Header:")
    print(f"  ARM9: offset={header['arm9_offset']:#x}, size={header['arm9_size']:#x}")
    print(f"  ARM7: offset={header['arm7_offset']:#x}, size={header['arm7_size']:#x}")
    print(f"  Overlay table: offset={header['overlay_table_offset']:#x}, size={header['overlay_table_size']:#x}")
    
    # Parse overlay table
    overlays = parse_overlay_table(data, header["overlay_table_offset"], header["overlay_table_size"])
    print(f"\nFound {len(overlays)} overlays in table")
    
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)
    
    # Extract overlays
    extracted = []
    for overlay in overlays:
        overlay_id = overlay["id"]
        name = OVERLAY_RANGES.get(overlay_id, {}).get("name", f"ov{overlay_id}")
        print(f"\nOverlay {overlay_id} ({name}):")
        print(f"  RAM: {overlay['ram_addr']:#010x} - {overlay['ram_addr'] + overlay['ram_size']:#010x}")
        print(f"  ROM: {overlay['rom_offset']:#010x} - {overlay['rom_offset'] + overlay['rom_size']:#010x}")
        print(f"  BSS: {overlay['bss_size']:#x} bytes")
        
        bin_path = extract_overlay(data, overlay, output_dir)
        extracted.append({
            "id": overlay_id,
            "name": name,
            "ram_addr": overlay["ram_addr"],
            "ram_size": overlay["ram_size"],
            "bss_size": overlay["bss_size"],
            "rom_offset": overlay["rom_offset"],
            "rom_size": overlay["rom_size"],
            "file": os.path.basename(bin_path) if bin_path else None
        })
    
    # Save metadata
    metadata_path = os.path.join(output_dir, "overlays.json")
    with open(metadata_path, "w") as f:
        json.dump({
            "header": {
                "arm9_offset": header["arm9_offset"],
                "arm9_size": header["arm9_size"],
                "arm7_offset": header["arm7_offset"],
                "arm7_size": header["arm7_size"],
            },
            "overlays": extracted
        }, f, indent=2)
    print(f"\nMetadata saved to {metadata_path}")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
